<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CostCenterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $costCenters = [
            ['coa_id' => 1, 'kode' => 'BLG-SPP-SP', 'nama' => 'CoGS Spareparts'],
            ['coa_id' => 1, 'kode' => 'BLG-SVC-C1', 'nama' => 'CoSR Maintenance Contract Area 1'],
            ['coa_id' => 1, 'kode' => 'BLG-SVC-N1', 'nama' => 'CoSR Non Maintenance Contract Area 1'],
            ['coa_id' => 1, 'kode' => 'BDG-SPP-SP', 'nama' => 'CoGS Spareparts'],
            ['coa_id' => 1, 'kode' => 'BDG-SVC-C1', 'nama' => 'CoSR Maintenance Contract Area 1'],
            ['coa_id' => 1, 'kode' => 'BDG-SVC-N1', 'nama' => 'CoSR Non Maintenance Contract Area 1'],
            ['coa_id' => 1, 'kode' => 'BJM-SPP-SP', 'nama' => 'CoGS Spareparts'],
            ['coa_id' => 1, 'kode' => 'BJM-SVC-C1', 'nama' => 'CoSR Maintenance Contract Area 1'],
            ['coa_id' => 1, 'kode' => 'BJM-SVC-N1', 'nama' => 'CoSR Non Maintenance Contract Area 1'],
            ['coa_id' => 1, 'kode' => 'JKT-SPP-SP', 'nama' => 'CoGS Spareparts'],
            ['coa_id' => 1, 'kode' => 'JKT-SVC-C1', 'nama' => 'CoSR Maintenance Contract Area 1'],
            ['coa_id' => 1, 'kode' => 'JKT-SVC-C2', 'nama' => 'CoSR Maintenance Contract Area 2'],
            ['coa_id' => 1, 'kode' => 'JKT-SVC-C3', 'nama' => 'CoSR Maintenance Contract SHN/Subsidiaries'],
            ['coa_id' => 1, 'kode' => 'JKT-SVC-N1', 'nama' => 'CoSR Non Maintenance Contract Area 1'],
            ['coa_id' => 1, 'kode' => 'JKT-SVC-N2', 'nama' => 'CoSR Non Maintenance Contract Area 2'],
            ['coa_id' => 1, 'kode' => 'JMB-SPP-SP', 'nama' => 'CoGS Spareparts'],
            ['coa_id' => 1, 'kode' => 'JMB-SVC-C1', 'nama' => 'CoSR Maintenance Contract Area 1'],
            ['coa_id' => 1, 'kode' => 'JMB-SVC-N1', 'nama' => 'CoSR Non Maintenance Contract Area 1'],
            ['coa_id' => 1, 'kode' => 'JYP-SPP-SP', 'nama' => 'CoGS Spareparts'],
            ['coa_id' => 1, 'kode' => 'JYP-SVC-C1', 'nama' => 'CoSR Maintenance Contract Area 1'],
            ['coa_id' => 1, 'kode' => 'JYP-SVC-N1', 'nama' => 'CoSR Non Maintenance Contract Area 1'],
            ['coa_id' => 1, 'kode' => 'MKS-SPP-SP', 'nama' => 'CoGS Spareparts'],
            ['coa_id' => 1, 'kode' => 'MKS-SVC-C1', 'nama' => 'CoSR Maintenance Contract Area 1'],
            ['coa_id' => 1, 'kode' => 'MKS-SVC-N1', 'nama' => 'CoSR Non Maintenance Contract Area 1'],
            ['coa_id' => 1, 'kode' => 'MDN-SPP-SP', 'nama' => 'CoGS Spareparts'],
            ['coa_id' => 1, 'kode' => 'MDN-SVC-C1', 'nama' => 'CoSR Maintenance Contract Area 1'],
            ['coa_id' => 1, 'kode' => 'MDN-SVC-N1', 'nama' => 'CoSR Non Maintenance Contract Area 1'],
            ['coa_id' => 1, 'kode' => 'PDG-SPP-SP', 'nama' => 'CoGS Spareparts'],
            ['coa_id' => 1, 'kode' => 'PDG-SVC-C1', 'nama' => 'CoSR Maintenance Contract Area 1'],
            ['coa_id' => 1, 'kode' => 'PDG-SVC-N1', 'nama' => 'CoSR Non Maintenance Contract Area 1'],
            ['coa_id' => 1, 'kode' => 'PLB-SPP-SP', 'nama' => 'CoGS Spareparts'],
            ['coa_id' => 1, 'kode' => 'PLB-SVC-C1', 'nama' => 'CoSR Maintenance Contract Area 1'],
            ['coa_id' => 1, 'kode' => 'PLB-SVC-N1', 'nama' => 'CoSR Non Maintenance Contract Area 1'],
            ['coa_id' => 1, 'kode' => 'PKB-SPP-SP', 'nama' => 'CoGS Spareparts'],
            ['coa_id' => 1, 'kode' => 'PKB-SVC-C1', 'nama' => 'CoSR Maintenance Contract Area 1'],
            ['coa_id' => 1, 'kode' => 'PKB-SVC-N1', 'nama' => 'CoSR Non Maintenance Contract Area 1'],
            ['coa_id' => 1, 'kode' => 'PTK-SPP-SP', 'nama' => 'CoGS Spareparts'],
            ['coa_id' => 1, 'kode' => 'PTK-SVC-C1', 'nama' => 'CoSR Maintenance Contract Area 1'],
            ['coa_id' => 1, 'kode' => 'PTK-SVC-N1', 'nama' => 'CoSR Non Maintenance Contract Area 1'],
            ['coa_id' => 1, 'kode' => 'SMD-SPP-SP', 'nama' => 'CoGS Spareparts'],
            ['coa_id' => 1, 'kode' => 'SMD-SVC-C1', 'nama' => 'CoSR Maintenance Contract Area 1'],
            ['coa_id' => 1, 'kode' => 'SMD-SVC-C2', 'nama' => 'CoSR Maintenance Contract Area 2'],
            ['coa_id' => 1, 'kode' => 'SMD-SVC-N1', 'nama' => 'CoSR Non Maintenance Contract Area 1'],
            ['coa_id' => 1, 'kode' => 'SMD-SVC-N2', 'nama' => 'CoSR Non Maintenance Contract Area 2'],
            ['coa_id' => 1, 'kode' => 'SMP-SPP-SP', 'nama' => 'CoGS Spareparts'],
            ['coa_id' => 1, 'kode' => 'SMP-SVC-C1', 'nama' => 'CoSR Maintenance Contract Area 1'],
            ['coa_id' => 1, 'kode' => 'SMP-SVC-N1', 'nama' => 'CoSR Non Maintenance Contract Area 1'],
            ['coa_id' => 1, 'kode' => 'SMG-SPP-SP', 'nama' => 'CoGS Spareparts'],
            ['coa_id' => 1, 'kode' => 'SMG-SVC-C1', 'nama' => 'CoSR Maintenance Contract Area 1'],
            ['coa_id' => 1, 'kode' => 'SMG-SVC-N1', 'nama' => 'CoSR Non Maintenance Contract Area 1'],
            ['coa_id' => 1, 'kode' => 'SBY-SPP-SP', 'nama' => 'CoGS Spareparts'],
            ['coa_id' => 1, 'kode' => 'SBY-SVC-C1', 'nama' => 'CoSR Maintenance Contract Area 1'],
            ['coa_id' => 1, 'kode' => 'SBY-SVC-N1', 'nama' => 'CoSR Non Maintenance Contract Area 1'],
            ['coa_id' => 2, 'kode' => 'BLG-EXP-UN', 'nama' => 'Branch Unit Bandar Lampung'],
            ['coa_id' => 2, 'kode' => 'BLG-EXP-SP', 'nama' => 'Branch Sparepart Bandar Lampung'],
            ['coa_id' => 2, 'kode' => 'BLG-EXP-SV', 'nama' => 'Branch Service Bandar Lampung'],
            ['coa_id' => 2, 'kode' => 'BDG-EXP-UN', 'nama' => 'Branch Unit Bandung'],
            ['coa_id' => 2, 'kode' => 'BDG-EXP-SP', 'nama' => 'Branch Sparepart Bandung'],
            ['coa_id' => 2, 'kode' => 'BDG-EXP-SV', 'nama' => 'Branch Service Bandung'],
            ['coa_id' => 2, 'kode' => 'BJM-EXP-UN', 'nama' => 'Branch Unit Banjarmasin'],
            ['coa_id' => 2, 'kode' => 'BJM-EXP-SP', 'nama' => 'Branch Sparepart Banjarmasin'],
            ['coa_id' => 2, 'kode' => 'BJM-EXP-SV', 'nama' => 'Branch Service Banjarmasin'],
            ['coa_id' => 2, 'kode' => 'BJM-EXP-DP', 'nama' => 'Depo Banjarmasin'],
            ['coa_id' => 2, 'kode' => 'HDO-006-03', 'nama' => 'Part Logistic Warehouse'],
            ['coa_id' => 2, 'kode' => 'HDO-002-01', 'nama' => 'Material Handling Sales'],
            ['coa_id' => 2, 'kode' => 'HDO-002-02', 'nama' => 'BT & Raymond Sales'],
            ['coa_id' => 2, 'kode' => 'HDO-003-01', 'nama' => 'Power Generation Sales'],
            ['coa_id' => 2, 'kode' => 'HDO-003-02', 'nama' => 'Air Solution Sales'],
            ['coa_id' => 2, 'kode' => 'HDO-004-01', 'nama' => 'Agro Sales'],
            ['coa_id' => 2, 'kode' => 'HDO-004-02', 'nama' => 'Construction & Crane Sales'],
            ['coa_id' => 2, 'kode' => 'HDO-006-01', 'nama' => 'Parts Sales'],
            ['coa_id' => 2, 'kode' => 'HDO-006-02', 'nama' => 'Parts Marketing'],
            ['coa_id' => 2, 'kode' => 'HDO-006-04', 'nama' => 'Key Account Product Support'],
            ['coa_id' => 2, 'kode' => 'HDO-007-01', 'nama' => 'Service Business & Customer Support'],
            ['coa_id' => 2, 'kode' => 'HDO-007-02', 'nama' => 'Service Technical Support & Warranty'],
            ['coa_id' => 2, 'kode' => 'HDO-007-03', 'nama' => 'Service Personal Development & Facilities'],
            ['coa_id' => 2, 'kode' => 'HDO-007-04', 'nama' => 'Service Marketing & Business Control'],
            ['coa_id' => 2, 'kode' => 'JKT-EXP-SP', 'nama' => 'Branch Sparepart Jakarta'],
            ['coa_id' => 2, 'kode' => 'JKT-EXP-SV', 'nama' => 'Branch Service Jakarta'],
            ['coa_id' => 2, 'kode' => 'JMB-EXP-UN', 'nama' => 'Branch Unit Jambi'],
            ['coa_id' => 2, 'kode' => 'JMB-EXP-SP', 'nama' => 'Branch Sparepart Jambi'],
            ['coa_id' => 2, 'kode' => 'JMB-EXP-SV', 'nama' => 'Branch Service Jambi'],
            ['coa_id' => 2, 'kode' => 'JYP-EXP-UN', 'nama' => 'Branch Unit Jayapura'],
            ['coa_id' => 2, 'kode' => 'JYP-EXP-SP', 'nama' => 'Branch Sparepart Jayapura'],
            ['coa_id' => 2, 'kode' => 'JYP-EXP-SV', 'nama' => 'Branch Service Jayapura'],
            ['coa_id' => 2, 'kode' => 'MKS-EXP-UN', 'nama' => 'Branch Unit Makassar'],
            ['coa_id' => 2, 'kode' => 'MKS-EXP-SP', 'nama' => 'Branch Sparepart Makassar'],
            ['coa_id' => 2, 'kode' => 'MKS-EXP-SV', 'nama' => 'Branch Service Makassar'],
            ['coa_id' => 2, 'kode' => 'MDN-EXP-UN', 'nama' => 'Branch Unit Medan'],
            ['coa_id' => 2, 'kode' => 'MDN-EXP-SP', 'nama' => 'Branch Sparepart Medan'],
            ['coa_id' => 2, 'kode' => 'MDN-EXP-SV', 'nama' => 'Branch Service Medan'],
            ['coa_id' => 2, 'kode' => 'PDG-EXP-UN', 'nama' => 'Branch Unit Padang'],
            ['coa_id' => 2, 'kode' => 'PDG-EXP-SP', 'nama' => 'Branch Sparepart Padang'],
            ['coa_id' => 2, 'kode' => 'PDG-EXP-SV', 'nama' => 'Branch Service Padang'],
            ['coa_id' => 2, 'kode' => 'PLB-EXP-UN', 'nama' => 'Branch Unit Palembang'],
            ['coa_id' => 2, 'kode' => 'PLB-EXP-SP', 'nama' => 'Branch Sparepart Palembang'],
            ['coa_id' => 2, 'kode' => 'PLB-EXP-SV', 'nama' => 'Branch Service Palembang'],
            ['coa_id' => 2, 'kode' => 'PLB-EXP-DP', 'nama' => 'Depo Palembang'],
            ['coa_id' => 2, 'kode' => 'PKB-EXP-UN', 'nama' => 'Branch Unit Pekanbaru'],
            ['coa_id' => 2, 'kode' => 'PKB-EXP-SP', 'nama' => 'Branch Sparepart Pekanbaru'],
            ['coa_id' => 2, 'kode' => 'PKB-EXP-SV', 'nama' => 'Branch Service Pekanbaru'],
            ['coa_id' => 2, 'kode' => 'PTK-EXP-UN', 'nama' => 'Branch Unit Pontianak'],
            ['coa_id' => 2, 'kode' => 'PTK-EXP-SP', 'nama' => 'Branch Sparepart Pontianak'],
            ['coa_id' => 2, 'kode' => 'PTK-EXP-SV', 'nama' => 'Branch Service Pontianak'],
            ['coa_id' => 2, 'kode' => 'SMD-EXP-UN', 'nama' => 'Branch Unit Samarinda'],
            ['coa_id' => 2, 'kode' => 'SMD-EXP-SP', 'nama' => 'Branch Sparepart Samarinda'],
            ['coa_id' => 2, 'kode' => 'SMD-EXP-SV', 'nama' => 'Branch Service Samarinda'],
            ['coa_id' => 2, 'kode' => 'SMP-EXP-UN', 'nama' => 'Branch Unit Sampit'],
            ['coa_id' => 2, 'kode' => 'SMP-EXP-SP', 'nama' => 'Branch Sparepart Sampit'],
            ['coa_id' => 2, 'kode' => 'SMP-EXP-SV', 'nama' => 'Branch Service Sampit'],
            ['coa_id' => 2, 'kode' => 'SMG-EXP-UN', 'nama' => 'Branch Unit Semarang'],
            ['coa_id' => 2, 'kode' => 'SMG-EXP-SP', 'nama' => 'Branch Sparepart Semarang'],
            ['coa_id' => 2, 'kode' => 'SMG-EXP-SV', 'nama' => 'Branch Service Semarang'],
            ['coa_id' => 2, 'kode' => 'SBY-EXP-UN', 'nama' => 'Branch Unit Surabaya'],
            ['coa_id' => 2, 'kode' => 'SBY-EXP-SP', 'nama' => 'Branch Sparepart Surabaya'],
            ['coa_id' => 2, 'kode' => 'SBY-EXP-SV', 'nama' => 'Branch Service Surabaya'],
            ['coa_id' => 3, 'kode' => 'BLG-EXP-AD', 'nama' => 'Branch Administration Bandar Lampung'],
            ['coa_id' => 3, 'kode' => 'BDG-EXP-AD', 'nama' => 'Branch Administration Bandung'],
            ['coa_id' => 3, 'kode' => 'BJM-EXP-AD', 'nama' => 'Branch Administration Banjarmasin'],
            ['coa_id' => 3, 'kode' => 'HDO-008-02', 'nama' => 'Accounting & Taxes'],
            ['coa_id' => 3, 'kode' => 'HDO-008-01', 'nama' => 'Finance'],
            ['coa_id' => 3, 'kode' => 'HDO-010-01', 'nama' => 'Internal Control'],
            ['coa_id' => 3, 'kode' => 'HDO-008-04', 'nama' => 'Information Technology'],
            ['coa_id' => 3, 'kode' => 'HDO-009-03', 'nama' => 'General Affair'],
            ['coa_id' => 3, 'kode' => 'HDO-009-02', 'nama' => 'Security, Environmental, Health, & Safety'],
            ['coa_id' => 3, 'kode' => 'HDO-009-01', 'nama' => 'Human Capital'],
            ['coa_id' => 3, 'kode' => 'HDO-010-06', 'nama' => 'Process Improvement & Digitalization'],
            ['coa_id' => 3, 'kode' => 'HDO-005-01', 'nama' => 'Marketing Support & Importation'],
            ['coa_id' => 3, 'kode' => 'HDO-010-04', 'nama' => 'Corporate Procurement'],
            ['coa_id' => 3, 'kode' => 'HDO-010-03', 'nama' => 'PDCA, AMS, & Innovation, ISO, SOP, Legal'],
            ['coa_id' => 3, 'kode' => 'HDO-005-02', 'nama' => 'Product Management Material Handling'],
            ['coa_id' => 3, 'kode' => 'HDO-005-03', 'nama' => 'Product Management Power & Air'],
            ['coa_id' => 3, 'kode' => 'HDO-005-04', 'nama' => 'Product Management Agro & Construction'],
            ['coa_id' => 3, 'kode' => 'HDO-005-05', 'nama' => 'Application Engineering'],
            ['coa_id' => 3, 'kode' => 'HDO-005-06', 'nama' => 'Marketing Communication'],
            ['coa_id' => 3, 'kode' => 'HDO-008-03', 'nama' => 'PDCA, Budget & Cost Control'],
            ['coa_id' => 3, 'kode' => 'HDO-010-02', 'nama' => 'Branch Support & Improvement'],
            ['coa_id' => 3, 'kode' => 'HDO-010-05', 'nama' => 'Executive Management'],
            ['coa_id' => 3, 'kode' => 'JMB-EXP-AD', 'nama' => 'Branch Administration Jambi'],
            ['coa_id' => 3, 'kode' => 'JYP-EXP-AD', 'nama' => 'Branch Administration Jayapura'],
            ['coa_id' => 3, 'kode' => 'MKS-EXP-AD', 'nama' => 'Branch Administration Makassar'],
            ['coa_id' => 3, 'kode' => 'MDN-EXP-AD', 'nama' => 'Branch Administration Medan'],
            ['coa_id' => 3, 'kode' => 'PDG-EXP-AD', 'nama' => 'Branch Administration Padang'],
            ['coa_id' => 3, 'kode' => 'PLB-EXP-AD', 'nama' => 'Branch Administration Palembang'],
            ['coa_id' => 3, 'kode' => 'PKB-EXP-AD', 'nama' => 'Branch Administration Pekanbaru'],
            ['coa_id' => 3, 'kode' => 'PTK-EXP-AD', 'nama' => 'Branch Administration Pontianak'],
            ['coa_id' => 3, 'kode' => 'SMD-EXP-AD', 'nama' => 'Branch Administration Samarinda'],
            ['coa_id' => 3, 'kode' => 'SMP-EXP-AD', 'nama' => 'Branch Administration Sampit'],
            ['coa_id' => 3, 'kode' => 'SMG-EXP-AD', 'nama' => 'Branch Administration Semarang'],
            ['coa_id' => 3, 'kode' => 'SBY-EXP-AD', 'nama' => 'Branch Administration Surabaya'],
            ['coa_id' => 3, 'kode' => 'JKT-EXP-AD', 'nama' => 'Branch Administration Jakarta'],
        ];

        DB::table('cost_centers')->insert($costCenters);
    }
}
